name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debugging
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" | wc -l  # should print a number greater than 1
          echo "$HOST"  # should print the IP address or DNS name of your EC2 instance
          echo "$USERNAME"  # should print the username you use to log into your EC2 instance

      - name: Deploy to server
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i $USERNAME@$HOST << EOF
            cd /home/ubuntu/vite-simple-deploy
            git pull
            npm ci
            npm run build
            # Restart your server here, if necessary
          EOF
        shell: bash
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
